<a href="https://colab.research.google.com/github/siddhuBikkina/titanic.2024008083/blob/main/FDS_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [ ]:
df = pd.read_excel("/content/Titanic-Dataset.xlsx")

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
df.shape

(891, 12)

In [ ]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
df["Age"] = df["Age"].fillna(df["Age"].median())

In [ ]:
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

In [ ]:
df.drop("Cabin", axis=1, inplace=True)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
le = LabelEncoder()

df["Sex"] = le.fit_transform(df["Sex"])

In [ ]:
df["Embarked"] = le.fit_transform(df["Embarked"])

In [ ]:
scaler = StandardScaler()

df[["Age","Fare"]] = scaler.fit_transform(df[["Age","Fare"]])

In [ ]:
Q1 = df["Fare"].quantile(0.25)
Q3 = df["Fare"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5*IQR
upper = Q3 + 1.5*IQR

outliers = df[(df["Fare"]<lower) | (df["Fare"]>upper)]

print(outliers)

     PassengerId  Survived  Pclass  \
1              2         1       1
27            28         0       1
31            32         1       1
34            35         0       1
52            53         1       1
..           ...       ...     ...
846          847         0       3
849          850         1       1
856          857         1       1
863          864         0       3
879          880         1       1

                                                  Name  Sex       Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...    0  0.663861      1
27                      Fortune, Mr. Charles Alexander    1 -0.796286      3
31      Spencer, Mrs. William Augustus (Marie Eugenie)    0 -0.104637      1
34                             Meyer, Mr. Edgar Joseph    1 -0.104637      1
52            Harper, Mrs. Henry Sleeper (Myna Haxtun)    0  1.509209      1
..                                                 ...  ...       ...    ...
846                           Sage, Mr. Douglas Bullen    1 -0.104637      8
849       Goldenberg, Mrs. Samuel L (Edwiga Grabowska)    0 -0.104637      1
856         Wick, Mrs. George Dennick (Mary Hitchcock)    0  1.201810      1
863                  Sage, Miss. Dorothy Edith "Dolly"    0 -0.104637      8
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)    0  2.047158      0

     Parch    Ticket      Fare  Embarked
1        0  PC 17599  0.786845         0
27       2     19950  4.647001         2
31       0  PC 17569  2.301729         0
34       0  PC 17604  1.006062         0
52       0  PC 17572  0.896497         0
..     ...       ...       ...       ...
846      2  CA. 2343  0.751946         2
849      0     17453  1.145664         0
856      1     36928  2.671118         2
863      2  CA. 2343  0.751946         2
879      1     11767  1.025945         0

[116 rows x 11 columns]

In [ ]:
df = df[(df["Fare"]>=lower) & (df["Fare"]<=upper)]

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",1,-0.565736,1,0,A/5 21171,-0.502445,2
2,3,1,3,"Heikkinen, Miss. Laina",0,-0.258337,0,0,STON/O2. 3101282,-0.488854,2
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,0.433312,1,0,113803,0.420730,2
4,5,0,3,"Allen, Mr. William Henry",1,0.433312,0,0,373450,-0.486337,2
5,6,0,3,"Moran, Mr. James",1,-0.104637,0,0,330877,-0.478116,1

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 775 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  775 non-null    int64
 1   Survived     775 non-null    int64
 2   Pclass       775 non-null    int64
 3   Name         775 non-null    object
 4   Sex          775 non-null    int64
 5   Age          775 non-null    float64
 6   SibSp        775 non-null    int64
 7   Parch        775 non-null    int64
 8   Ticket       775 non-null    object
 9   Fare         775 non-null    float64
 10  Embarked     775 non-null    int64
dtypes: float64(2), int64(7), object(2)
memory usage: 72.7+ KB

In [ ]:
df.describe()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
count,775.000000,775.000000,775.00000,775.000000,775.000000,775.000000,775.000000,775.000000,775.000000
mean,445.806452,0.339355,2.48000,0.685161,-0.047099,0.437419,0.340645,-0.289579,1.603871
std,260.116285,0.473796,0.73439,0.464752,0.982304,0.899838,0.785914,0.273391,0.734344
min,1.000000,0.000000,1.00000,0.000000,-2.224156,0.000000,0.000000,-0.648422,0.000000
25%,213.500000,0.000000,2.00000,0.000000,-0.565736,0.000000,0.000000,-0.489442,2.000000
50%,450.000000,0.000000,3.00000,1.000000,-0.104637,0.000000,0.000000,-0.386671,2.000000
75%,670.500000,1.000000,3.00000,1.000000,0.356462,1.000000,0.000000,-0.124920,2.000000
max,891.000000,1.000000,3.00000,1.000000,3.891554,5.000000,6.000000,0.660333,2.000000

In [ ]:
df.to_csv("Titanic_Preprocessed.csv", index=False)